import { Island } from "Island.slint";
import { IslandData, Assets } from "global.slint";

export { IslandData, Assets }

import "../../assets/fonts/Satoshi-Light.otf";

export component Shell inherits Window {
    title: "Lumen";

    background: transparent;

    default-font-family: "Satoshi Light";
    default-font-weight: 400;
    
    in property <length> island-width;
    in property <length> island-height;
    in property <length> island-radius;

    in property <length> island-y;

    callback tick();

    Island {
        width: island-width;
        height: island-height + 8px;

        radius: island-radius;

        y-anchor: island-y;

        x: (parent.width - self.width) / 2;
    }

    Timer {
        interval: 33ms;
        running: true;

        triggered => {
            root.tick()
        }
    }
}